#!/usr/bin/env node
/**
 * Build static RSS files from the live Squarespace feeds, rewriting
 * podcast enclosures to first-party /audio/<slug> URLs.
 *
 * Usage: npm run generate-feeds
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import * as cheerio from "cheerio";

const ROOT = new URL("..", import.meta.url).pathname;
const SITE = "https://jamesmchristensen.com";
const BLOG_RSS = `${SITE}/blog?format=rss`;
const PODCAST_RSS = `${SITE}/podcast?format=rss`;
const UA =
  "Mozilla/5.0 (compatible; RosevilleSiteImporter/1.0; +https://github.com/443jmc/banana)";
const MANIFEST_PATH = join(ROOT, "scripts/data/audio-manifest.json");
const PODCAST_COVER = `${SITE}/images/site/podcast-cover.png`;

async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.text();
}

async function loadXml(url, cacheName) {
  const cachePath = join(ROOT, "scripts/.cache", cacheName);
  try {
    const xml = await fetchText(url);
    await mkdir(dirname(cachePath), { recursive: true });
    await writeFile(cachePath, xml);
    return xml;
  } catch (err) {
    if (existsSync(cachePath)) {
      console.warn(`Live fetch failed (${err.message}); using ${cachePath}`);
      return readFile(cachePath, "utf8");
    }
    throw err;
  }
}

function escapeAttr(value) {
  return String(value).replace(/&/g, "&amp;").replace(/"/g, "&quot;");
}

async function loadManifest(passed) {
  if (passed) return passed;
  if (!existsSync(MANIFEST_PATH)) return { items: [] };
  return JSON.parse(await readFile(MANIFEST_PATH, "utf8"));
}

function rewriteItunesImage(xml) {
  return xml.replace(
    /<itunes:image\b[^>]*href="https?:\/\/[^"]*squarespace[^"]*"[^>]*\/?>/g,
    `<itunes:image href="${escapeAttr(PODCAST_COVER)}"/>`
  );
}

function rewriteGenerator(xml) {
  return xml.replace(
    /<generator>Site-Server v@build\.version@ \(http:\/\/www\.squarespace\.com\)<\/generator>/g,
    "<generator>Roseville Couples Counseling</generator>"
  );
}

function rewriteComment(xml) {
  return xml.replace(
    /<!--Generated by Site-Server v@build\.version@ \(http:\/\/www\.squarespace\.com\) on [^>]+-->/,
    "<!-- Generated for jamesmchristensen.com Squarespace cutover -->"
  );
}

async function rewritePodcastEnclosures(xml, manifest) {
  const byOriginal = new Map();
  for (const item of manifest.items || []) {
    if (item.originalUrl) byOriginal.set(item.originalUrl, item);
  }

  return xml.replace(/<enclosure\b[^>]*\/?>/g, (tag) => {
    const urlMatch = tag.match(/\burl="([^"]+)"/);
    if (!urlMatch) return tag;
    const oldUrl = urlMatch[1];
    const mapped = byOriginal.get(oldUrl);
    if (!mapped?.publicUrl) {
      throw new Error(`No first-party mapping for enclosure ${oldUrl}`);
    }
    return `<enclosure url="${escapeAttr(mapped.publicUrl)}" length="${mapped.bytes || 0}" type="${escapeAttr(mapped.type || "audio/mpeg")}"/>`;
  });
}

function rewriteSquarespaceAudioUrls(xml, manifest) {
  let out = xml;
  for (const item of manifest.items || []) {
    if (item.originalUrl && item.publicUrl) {
      out = out.split(item.originalUrl).join(item.publicUrl);
    }
  }
  if (/static1\.squarespace\.com/i.test(out) && /<enclosure/i.test(out)) {
    const leftover = out.match(/https?:\/\/static1\.squarespace\.com[^"'<\s]+/g) || [];
    const audioLeft = leftover.filter((u) => /\.(mp3|mp4|m4a)(\?|$)/i.test(u) || /\/t\/[0-9a-f]+\//i.test(u));
    if (audioLeft.length) {
      throw new Error(`Squarespace audio URLs remain in podcast feed:\n${audioLeft.join("\n")}`);
    }
  }
  return out;
}

function assertFeed(xml, { title, minItems, name }) {
  const $ = cheerio.load(xml, { xmlMode: true });
  const actualTitle = $("channel > title").first().text();
  const items = $("channel > item").length;
  if (actualTitle !== title) {
    throw new Error(`${name} title is "${actualTitle}", expected "${title}"`);
  }
  if (items < minItems) {
    throw new Error(`${name} has ${items} items, expected at least ${minItems}`);
  }
}

export async function generateFeeds({ podcastXml, blogXml, manifest } = {}) {
  await mkdir(join(ROOT, "public/blog"), { recursive: true });
  await mkdir(join(ROOT, "public/podcast"), { recursive: true });

  const loadedManifest = await loadManifest(manifest);
  const blog = blogXml || (await loadXml(BLOG_RSS, "blog.rss.xml"));
  const podcast = podcastXml || (await loadXml(PODCAST_RSS, "podcast.rss.xml"));

  let blogOut = rewriteComment(rewriteGenerator(blog));
  assertFeed(blogOut, { title: "Roseville Couples Therapy Blog", minItems: 20, name: "Blog" });
  await writeFile(join(ROOT, "public/blog/rss.xml"), blogOut);
  console.log("Wrote public/blog/rss.xml");

  let podcastOut = rewriteComment(rewriteGenerator(podcast));
  podcastOut = rewriteItunesImage(podcastOut);
  podcastOut = await rewritePodcastEnclosures(podcastOut, loadedManifest);
  podcastOut = rewriteSquarespaceAudioUrls(podcastOut, loadedManifest);
  assertFeed(podcastOut, { title: "Balance your Brain", minItems: 39, name: "Podcast" });
  if (/itunes:author>\s*James Christensen\s*</.test(podcastOut) === false && !podcastOut.includes("<itunes:author>James Christensen</itunes:author>")) {
    throw new Error("Podcast feed missing itunes:author James Christensen");
  }
  await writeFile(join(ROOT, "public/podcast/rss.xml"), podcastOut);
  console.log("Wrote public/podcast/rss.xml");

  return { blogPath: "public/blog/rss.xml", podcastPath: "public/podcast/rss.xml" };
}

const isMain =
  process.argv[1] &&
  (import.meta.url === new URL(process.argv[1], "file://").href ||
    process.argv[1].endsWith("generate-feeds.mjs"));

if (isMain) {
  generateFeeds().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
